#### Importing Dependencies

In [10]:
import os
import sys

path = os.path.abspath(os.path.join(".."))
if path not in sys.path:
    sys.path.append(path)
import warnings

warnings.filterwarnings("ignore")

In [11]:
import numpy as np
import yfinance as yf

from src import Backtester
from src import HOLD, EntrySignal, ExitSignal

#### Downloading OHLC data and processing it

In [12]:
TICKER = "BTC-USD"
START_DATE = "2015-01-01"
END_DATE = "2025-01-01"

In [13]:
df = yf.download(TICKER, start=START_DATE, end=END_DATE)

if df is None:
    raise ValueError("Failed to download data from yfinance.")

df.columns = df.columns.get_level_values(0)
df[["Close", "High", "Low", "Open"]] = (
    df[["Close", "High", "Low", "Open"]].astype(float).apply(np.round, args=(4,))
)
df.drop(columns=["Volume"], inplace=True)
df[
    [
        "Entry_Signal",
        "Exit_Signal",
        "Edit_Signal",
    ]
] = HOLD
df[
    [
        "Signal_Volume",
        "Signal_Stop_Loss",
        "Signal_Limit",
    ]
] = 0.0
df["Signal_Volume"] = df["Signal_Volume"].astype(int)

[*********************100%***********************]  1 of 1 completed

In [14]:
df.head()

Price,Close,High,Low,Open,Entry_Signal,Exit_Signal,Edit_Signal,Signal_Volume,Signal_Stop_Loss,Signal_Limit
Date,,,,,,,,,,
2015-01-01,314.249,320.435,314.003,320.435,2,2,2,0,0.0,0.0
2015-01-02,315.032,315.839,313.565,314.079,2,2,2,0,0.0,0.0
2015-01-03,281.082,315.150,281.082,314.846,2,2,2,0,0.0,0.0
2015-01-04,264.195,287.230,257.612,281.146,2,2,2,0,0.0,0.0
2015-01-05,274.474,278.341,265.084,265.084,2,2,2,0,0.0,0.0

In [15]:
short_window = 50
long_window = 100
trade_volume = 5
df["short_mavg"] = df["Close"].rolling(window=short_window, min_periods=1).mean()
df["long_mavg"] = df["Close"].rolling(window=long_window, min_periods=1).mean()
df.head()

Price,Close,High,Low,Open,Entry_Signal,Exit_Signal,Edit_Signal,Signal_Volume,Signal_Stop_Loss,Signal_Limit,short_mavg,long_mavg
Date,,,,,,,,,,,,
2015-01-01,314.249,320.435,314.003,320.435,2,2,2,0,0.0,0.0,314.249000,314.249000
2015-01-02,315.032,315.839,313.565,314.079,2,2,2,0,0.0,0.0,314.640500,314.640500
2015-01-03,281.082,315.150,281.082,314.846,2,2,2,0,0.0,0.0,303.454333,303.454333
2015-01-04,264.195,287.230,257.612,281.146,2,2,2,0,0.0,0.0,293.639500,293.639500
2015-01-05,274.474,278.341,265.084,265.084,2,2,2,0,0.0,0.0,289.806400,289.806400

In [16]:
longs = (df["short_mavg"] > df["long_mavg"]) & (
    df["short_mavg"].shift(1) <= df["long_mavg"].shift(1)
)
shorts = (df["short_mavg"] < df["long_mavg"]) & (
    df["short_mavg"].shift(1) >= df["long_mavg"].shift(1)
)

df.loc[longs, ["Entry_Signal", "Exit_Signal", "Signal_Volume"]] = [
    EntrySignal.BUY.value,
    ExitSignal.CLOSE_SELL.value,
    trade_volume,
]
df.loc[shorts, ["Entry_Signal", "Exit_Signal", "Signal_Volume"]] = [
    EntrySignal.SELL.value,
    ExitSignal.CLOSE_BUY.value,
    trade_volume,
]
df["Entry_Signal"] = df["Entry_Signal"].shift(1).fillna(HOLD).astype(int)
df["Exit_Signal"] = df["Exit_Signal"].shift(1).fillna(HOLD).astype(int)
df["Signal_Volume"] = df["Signal_Volume"].shift(1).fillna(0).astype(int)

In [17]:
df.drop(columns=["short_mavg", "long_mavg"], inplace=True)
df.head()

Price,Close,High,Low,Open,Entry_Signal,Exit_Signal,Edit_Signal,Signal_Volume,Signal_Stop_Loss,Signal_Limit
Date,,,,,,,,,,
2015-01-01,314.249,320.435,314.003,320.435,2,2,2,0,0.0,0.0
2015-01-02,315.032,315.839,313.565,314.079,2,2,2,0,0.0,0.0
2015-01-03,281.082,315.150,281.082,314.846,2,2,2,0,0.0,0.0
2015-01-04,264.195,287.230,257.612,281.146,2,2,2,0,0.0,0.0
2015-01-05,274.474,278.341,265.084,265.084,2,2,2,0,0.0,0.0

In [18]:
starting_balance = 100000.0
currency = "USD"
bt = Backtester(
    starting_balance=starting_balance, ohlc_data=df, currency=currency, symbol=TICKER
)

In [19]:
bt.run_backtest()

,State,Order_Type,Volume,Open_Time,Open_Price,Close_Time,Close_Price,Stop_Loss,Limit,Info,Profit,Commission,Net_Profit,Cumulative_Profit,Balance,Drawdown
0,Closed,Sell,5,2015-02-21 00:00:00,243.752,2015-03-21 00:00:00,261.644,0.0,0.0,,-89.46,-0.0,-89.46,-89.46,99910.54,NaN
1,Closed,Buy,5,2015-03-21 00:00:00,261.644,2015-05-02 00:00:00,232.341,0.0,0.0,,-146.51,-0.0,-146.51,-235.97,99764.03,NaN
2,Closed,Sell,5,2015-05-02 00:00:00,232.341,2015-07-03 00:00:00,255.459,0.0,0.0,,-115.59,-0.0,-115.59,-351.56,99648.44,NaN
3,Closed,Buy,5,2015-07-03 00:00:00,255.459,2015-09-11 00:00:00,238.329,0.0,0.0,,-85.65,-0.0,-85.65,-437.21,99562.79,NaN
4,Closed,Sell,5,2015-09-11 00:00:00,238.329,2015-11-02 00:00:00,325.942,0.0,0.0,,-438.06,-0.0,-438.06,-875.27,99124.73,NaN
5,Closed,Buy,5,2015-11-02 00:00:00,325.942,2016-02-26 00:00:00,424.629,0.0,0.0,,493.44,-0.0,493.44,-381.83,99618.17,NaN
6,Closed,Sell,5,2016-02-26 00:00:00,424.629,2016-03-28 00:00:00,426.548,0.0,0.0,,-9.59,-0.0,-9.59,-391.42,99608.58,NaN
7,Closed,Buy,5,2016-03-28 00:00:00,426.548,2016-08-30 00:00:00,574.114,0.0,0.0,,737.83,-0.0,737.83,346.41,100346.41,NaN
8,Closed,Sell,5,2016-08-30 00:00:00,574.114,2016-10-20 00:00:00,630.663,0.0,0.0,,-282.74,-0.0,-282.74,63.67,100063.67,NaN
9,Closed,Buy,5,2016-10-20 00:00:00,630.663,2018-02-16 00:00:00,10135.7002,0.0,0.0,,47525.19,-0.0,47525.19,47588.86,147588.86,NaN
10,Closed,Sell,5,2018-02-16 00:00:00,10135.7002,2018-06-08 00:00:00,7685.1401,0.0,0.0,,12252.80,-0.0,12252.8,59841.66,159841.66,NaN
11,Closed,Buy,5,2018-06-08 00:00:00,7685.1401,2018-06-17 00:00:00,6545.5298,0.0,0.0,,-5698.05,-0.0,-5698.05,54143.61,154143.61,NaN
12,Closed,Sell,5,2018-06-17 00:00:00,6545.5298,2018-08-29 00:00:00,7091.71,0.0,0.0,,-2730.90,-0.0,-2730.9,51412.71,151412.71,NaN
13,Closed,Buy,5,2018-08-29 00:00:00,7091.71,2018-09-17 00:00:00,6514.0601,0.0,0.0,,-2888.25,-0.0,-2888.25,48524.46,148524.46,NaN
14,Closed,Sell,5,2018-09-17 00:00:00,6514.0601,2019-03-14 00:00:00,3905.5769,0.0,0.0,,13042.42,-0.0,13042.42,61566.88,161566.88,NaN
15,Closed,Buy,5,2019-03-14 00:00:00,3905.5769,2019-09-21 00:00:00,10183.6484,0.0,0.0,,31390.36,-0.0,31390.36,92957.24,192957.24,NaN
16,Closed,Sell,5,2019-09-21 00:00:00,10183.6484,2020-02-05 00:00:00,9183.416,0.0,0.0,,5001.16,-0.0,5001.16,97958.4,197958.4,NaN
17,Closed,Buy,5,2020-02-05 00:00:00,9183.416,2020-03-28 00:00:00,6467.2539,0.0,0.0,,-13580.81,-0.0,-13580.81,84377.59,184377.59,NaN
18,Closed,Sell,5,2020-03-28 00:00:00,6467.2539,2020-05-21 00:00:00,9522.7402,0.0,0.0,,-15277.43,-0.0,-15277.43,69100.16,169100.16,NaN
19,Closed,Buy,5,2020-05-21 00:00:00,9522.7402,2020-10-19 00:00:00,11495.0381,0.0,0.0,,9861.49,-0.0,9861.49,78961.65,178961.65,NaN
20,Closed,Sell,5,2020-10-19 00:00:00,11495.0381,2020-10-28 00:00:00,13654.2148,0.0,0.0,,-10795.88,-0.0,-10795.88,68165.77,168165.77,NaN
21,Closed,Buy,5,2020-10-28 00:00:00,13654.2148,2021-05-24 00:00:00,34700.3633,0.0,0.0,,105230.74,-0.0,105230.74,173396.51,273396.51,NaN
22,Closed,Sell,5,2021-05-24 00:00:00,34700.3633,2021-08-20 00:00:00,46723.1211,0.0,0.0,,-60113.79,-0.0,-60113.79,113282.72,213282.72,NaN
23,Closed,Buy,5,2021-08-20 00:00:00,46723.1211,2021-12-28 00:00:00,50679.8594,0.0,0.0,,19783.69,-0.0,19783.69,133066.41,233066.41,NaN
24,Closed,Sell,5,2021-12-28 00:00:00,50679.8594,2022-04-08 00:00:00,43505.1367,0.0,0.0,,35873.61,-0.0,35873.61,168940.02,268940.02,NaN
25,Closed,Buy,5,2022-04-08 00:00:00,43505.1367,2022-05-13 00:00:00,29030.9102,0.0,0.0,,-72371.13,-0.0,-72371.13,96568.89,196568.89,NaN
26,Closed,Sell,5,2022-05-13 00:00:00,29030.9102,2022-09-16 00:00:00,19704.0059,0.0,0.0,,46634.52,-0.0,46634.52,143203.41,243203.41,NaN
27,Closed,Buy,5,2022-09-16 00:00:00,19704.0059,2022-09-23 00:00:00,19412.4004,0.0,0.0,,-1458.03,-0.0,-1458.03,141745.38,241745.38,NaN
28,Closed,Sell,5,2022-09-23 00:00:00,19412.4004,2023-01-26 00:00:00,23108.9551,0.0,0.0,,-18482.77,-0.0,-18482.77,123262.61,223262.61,NaN
29,Closed,Buy,5,2023-01-26 00:00:00,23108.9551,2023-06-16 00:00:00,25575.2832,0.0,0.0,,12331.64,-0.0,12331.64,135594.25,235594.25,NaN
30,Closed,Sell,5,2023-06-16 00:00:00,25575.2832,2023-07-14 00:00:00,31474.7207,0.0,0.0,,-29497.19,-0.0,-29497.19,106097.06,206097.06,NaN
31,Closed,Buy,5,2023-07-14 00:00:00,31474.7207,2023-09-03 00:00:00,25869.4727,0.0,0.0,,-28026.24,-0.0,-28026.24,78070.82,178070.82,NaN
32,Closed,Sell,5,2023-09-03 00:00:00,25869.4727,2023-10-29 00:00:00,34089.3711,0.0,0.0,,-41099.49,-0.0,-41099.49,36971.33,136971.33,NaN
33,Closed,Buy,5,2023-10-29 00:00:00,34089.3711,2024-05-30 00:00:00,67576.0859,0.0,0.0,,167433.57,-0.0,167433.57,204404.9,304404.9,NaN
34,Closed,Sell,5,2024-05-30 00:00:00,67576.0859,2024-06-22 00:00:00,64113.8633,0.0,0.0,,17311.11,-0.0,17311.11,221716.01,321716.01,NaN
35,Closed,Buy,5,2024-06-22 00:00:00,64113.8633,2024-07-12 00:00:00,57341.1953,0.0,0.0,,-33863.34,-0.0,-33863.34,187852.67,287852.67,NaN
36,Closed,Sell,5,2024-07-12 00:00:00,57341.1953,2024-10-23 00:00:00,67362.375,0.0,0.0,,-50105.90,-0.0,-50105.9,137746.77,237746.77,NaN
37,Closed,Buy,5,2024-10-23 00:00:00,67362.375,2024-12-31 00:00:00,93429.2031,0.0,0.0,,130334.14,-0.0,130334.14,268080.91,368080.91,NaN

In [20]:
bt.evaluate_backtest()

RESULTS
========================================
Biggest Win: 167433.57 USD
Biggest Loss: -72371.13 USD

Winning Trades

,State,Order_Type,Volume,Open_Time,Open_Price,Close_Time,Close_Price,Stop_Loss,Limit,Info,Profit,Commission,Net_Profit,Cumulative_Profit,Balance,Drawdown
5,Closed,Buy,5,2015-11-02 00:00:00,325.942,2016-02-26 00:00:00,424.629,0.0,0.0,,493.44,-0.0,493.44,-381.83,99618.17,NaN
7,Closed,Buy,5,2016-03-28 00:00:00,426.548,2016-08-30 00:00:00,574.114,0.0,0.0,,737.83,-0.0,737.83,346.41,100346.41,NaN
9,Closed,Buy,5,2016-10-20 00:00:00,630.663,2018-02-16 00:00:00,10135.7002,0.0,0.0,,47525.19,-0.0,47525.19,47588.86,147588.86,NaN
10,Closed,Sell,5,2018-02-16 00:00:00,10135.7002,2018-06-08 00:00:00,7685.1401,0.0,0.0,,12252.80,-0.0,12252.8,59841.66,159841.66,NaN
14,Closed,Sell,5,2018-09-17 00:00:00,6514.0601,2019-03-14 00:00:00,3905.5769,0.0,0.0,,13042.42,-0.0,13042.42,61566.88,161566.88,NaN
15,Closed,Buy,5,2019-03-14 00:00:00,3905.5769,2019-09-21 00:00:00,10183.6484,0.0,0.0,,31390.36,-0.0,31390.36,92957.24,192957.24,NaN
16,Closed,Sell,5,2019-09-21 00:00:00,10183.6484,2020-02-05 00:00:00,9183.416,0.0,0.0,,5001.16,-0.0,5001.16,97958.4,197958.4,NaN
19,Closed,Buy,5,2020-05-21 00:00:00,9522.7402,2020-10-19 00:00:00,11495.0381,0.0,0.0,,9861.49,-0.0,9861.49,78961.65,178961.65,NaN
21,Closed,Buy,5,2020-10-28 00:00:00,13654.2148,2021-05-24 00:00:00,34700.3633,0.0,0.0,,105230.74,-0.0,105230.74,173396.51,273396.51,NaN
23,Closed,Buy,5,2021-08-20 00:00:00,46723.1211,2021-12-28 00:00:00,50679.8594,0.0,0.0,,19783.69,-0.0,19783.69,133066.41,233066.41,NaN
24,Closed,Sell,5,2021-12-28 00:00:00,50679.8594,2022-04-08 00:00:00,43505.1367,0.0,0.0,,35873.61,-0.0,35873.61,168940.02,268940.02,NaN
26,Closed,Sell,5,2022-05-13 00:00:00,29030.9102,2022-09-16 00:00:00,19704.0059,0.0,0.0,,46634.52,-0.0,46634.52,143203.41,243203.41,NaN
29,Closed,Buy,5,2023-01-26 00:00:00,23108.9551,2023-06-16 00:00:00,25575.2832,0.0,0.0,,12331.64,-0.0,12331.64,135594.25,235594.25,NaN
33,Closed,Buy,5,2023-10-29 00:00:00,34089.3711,2024-05-30 00:00:00,67576.0859,0.0,0.0,,167433.57,-0.0,167433.57,204404.9,304404.9,NaN
34,Closed,Sell,5,2024-05-30 00:00:00,67576.0859,2024-06-22 00:00:00,64113.8633,0.0,0.0,,17311.11,-0.0,17311.11,221716.01,321716.01,NaN
37,Closed,Buy,5,2024-10-23 00:00:00,67362.375,2024-12-31 00:00:00,93429.2031,0.0,0.0,,130334.14,-0.0,130334.14,268080.91,368080.91,NaN

Losing Trades

,State,Order_Type,Volume,Open_Time,Open_Price,Close_Time,Close_Price,Stop_Loss,Limit,Info,Profit,Commission,Net_Profit,Cumulative_Profit,Balance,Drawdown
0,Closed,Sell,5,2015-02-21 00:00:00,243.752,2015-03-21 00:00:00,261.644,0.0,0.0,,-89.46,-0.0,-89.46,-89.46,99910.54,NaN
1,Closed,Buy,5,2015-03-21 00:00:00,261.644,2015-05-02 00:00:00,232.341,0.0,0.0,,-146.51,-0.0,-146.51,-235.97,99764.03,NaN
2,Closed,Sell,5,2015-05-02 00:00:00,232.341,2015-07-03 00:00:00,255.459,0.0,0.0,,-115.59,-0.0,-115.59,-351.56,99648.44,NaN
3,Closed,Buy,5,2015-07-03 00:00:00,255.459,2015-09-11 00:00:00,238.329,0.0,0.0,,-85.65,-0.0,-85.65,-437.21,99562.79,NaN
4,Closed,Sell,5,2015-09-11 00:00:00,238.329,2015-11-02 00:00:00,325.942,0.0,0.0,,-438.06,-0.0,-438.06,-875.27,99124.73,NaN
6,Closed,Sell,5,2016-02-26 00:00:00,424.629,2016-03-28 00:00:00,426.548,0.0,0.0,,-9.59,-0.0,-9.59,-391.42,99608.58,NaN
8,Closed,Sell,5,2016-08-30 00:00:00,574.114,2016-10-20 00:00:00,630.663,0.0,0.0,,-282.74,-0.0,-282.74,63.67,100063.67,NaN
11,Closed,Buy,5,2018-06-08 00:00:00,7685.1401,2018-06-17 00:00:00,6545.5298,0.0,0.0,,-5698.05,-0.0,-5698.05,54143.61,154143.61,NaN
12,Closed,Sell,5,2018-06-17 00:00:00,6545.5298,2018-08-29 00:00:00,7091.71,0.0,0.0,,-2730.90,-0.0,-2730.9,51412.71,151412.71,NaN
13,Closed,Buy,5,2018-08-29 00:00:00,7091.71,2018-09-17 00:00:00,6514.0601,0.0,0.0,,-2888.25,-0.0,-2888.25,48524.46,148524.46,NaN
17,Closed,Buy,5,2020-02-05 00:00:00,9183.416,2020-03-28 00:00:00,6467.2539,0.0,0.0,,-13580.81,-0.0,-13580.81,84377.59,184377.59,NaN
18,Closed,Sell,5,2020-03-28 00:00:00,6467.2539,2020-05-21 00:00:00,9522.7402,0.0,0.0,,-15277.43,-0.0,-15277.43,69100.16,169100.16,NaN
20,Closed,Sell,5,2020-10-19 00:00:00,11495.0381,2020-10-28 00:00:00,13654.2148,0.0,0.0,,-10795.88,-0.0,-10795.88,68165.77,168165.77,NaN
22,Closed,Sell,5,2021-05-24 00:00:00,34700.3633,2021-08-20 00:00:00,46723.1211,0.0,0.0,,-60113.79,-0.0,-60113.79,113282.72,213282.72,NaN
25,Closed,Buy,5,2022-04-08 00:00:00,43505.1367,2022-05-13 00:00:00,29030.9102,0.0,0.0,,-72371.13,-0.0,-72371.13,96568.89,196568.89,NaN
27,Closed,Buy,5,2022-09-16 00:00:00,19704.0059,2022-09-23 00:00:00,19412.4004,0.0,0.0,,-1458.03,-0.0,-1458.03,141745.38,241745.38,NaN
28,Closed,Sell,5,2022-09-23 00:00:00,19412.4004,2023-01-26 00:00:00,23108.9551,0.0,0.0,,-18482.77,-0.0,-18482.77,123262.61,223262.61,NaN
30,Closed,Sell,5,2023-06-16 00:00:00,25575.2832,2023-07-14 00:00:00,31474.7207,0.0,0.0,,-29497.19,-0.0,-29497.19,106097.06,206097.06,NaN
31,Closed,Buy,5,2023-07-14 00:00:00,31474.7207,2023-09-03 00:00:00,25869.4727,0.0,0.0,,-28026.24,-0.0,-28026.24,78070.82,178070.82,NaN
32,Closed,Sell,5,2023-09-03 00:00:00,25869.4727,2023-10-29 00:00:00,34089.3711,0.0,0.0,,-41099.49,-0.0,-41099.49,36971.33,136971.33,NaN
35,Closed,Buy,5,2024-06-22 00:00:00,64113.8633,2024-07-12 00:00:00,57341.1953,0.0,0.0,,-33863.34,-0.0,-33863.34,187852.67,287852.67,NaN
36,Closed,Sell,5,2024-07-12 00:00:00,57341.1953,2024-10-23 00:00:00,67362.375,0.0,0.0,,-50105.90,-0.0,-50105.9,137746.77,237746.77,NaN

Average Win: 40952.36 USD
Average Loss: -17598.04 USD
Total Winning Trades: 16
Total Losing Trades: 22
Win Rate: 42.11%
Profit Factor: 1.69
Risk-Reward Ratio: 2.33

  Order_Type Net_Profit
0        Buy  367004.08
1       Sell  -98923.17

Maximum Drawdown: 136425.18 USD
Sharpe Ratio: 0.36
Sortino Ratio: 0.12
Total Net Profit: 268080.91 USD
Final Balance: 368080.91 USD
========================================

Results(biggest_win=167433.57, biggest_loss=-72371.13, avg_win=40952.356875000005, avg_loss=-17598.036363636365, total_win_trades=16, total_loss_trades=22, win_rate=42.10526315789473, gross_profit=655237.7100000001, gross_loss=387156.80000000005, profit_factor=1.6924349772495277, risk_reward_ratio=2.3270980937181007, max_drawdown=136425.18000000002, sharpe_ratio=0.3572638453975766, sortino_ratio=0.11753514530090965, total_net_profit=268080.91000000003, final_balance=368080.91000000003)

In [21]:
bt.visualize_backtest()

In [22]:
bt.export_to_json("crossover.json")

RESULTS
========================================
Biggest Win: 167433.57 USD
Biggest Loss: -72371.13 USD

Winning Trades

,State,Order_Type,Volume,Open_Time,Open_Price,Close_Time,Close_Price,Stop_Loss,Limit,Info,Profit,Commission,Net_Profit,Cumulative_Profit,Balance,Drawdown
5,Closed,Buy,5,2015-11-02 00:00:00,325.942,2016-02-26 00:00:00,424.629,0.0,0.0,,493.44,-0.0,493.44,-381.83,99618.17,292.37
7,Closed,Buy,5,2016-03-28 00:00:00,426.548,2016-08-30 00:00:00,574.114,0.0,0.0,,737.83,-0.0,737.83,346.41,100346.41,0.0
9,Closed,Buy,5,2016-10-20 00:00:00,630.663,2018-02-16 00:00:00,10135.7002,0.0,0.0,,47525.19,-0.0,47525.19,47588.86,147588.86,0.0
10,Closed,Sell,5,2018-02-16 00:00:00,10135.7002,2018-06-08 00:00:00,7685.1401,0.0,0.0,,12252.80,-0.0,12252.8,59841.66,159841.66,0.0
14,Closed,Sell,5,2018-09-17 00:00:00,6514.0601,2019-03-14 00:00:00,3905.5769,0.0,0.0,,13042.42,-0.0,13042.42,61566.88,161566.88,0.0
15,Closed,Buy,5,2019-03-14 00:00:00,3905.5769,2019-09-21 00:00:00,10183.6484,0.0,0.0,,31390.36,-0.0,31390.36,92957.24,192957.24,0.0
16,Closed,Sell,5,2019-09-21 00:00:00,10183.6484,2020-02-05 00:00:00,9183.416,0.0,0.0,,5001.16,-0.0,5001.16,97958.4,197958.4,0.0
19,Closed,Buy,5,2020-05-21 00:00:00,9522.7402,2020-10-19 00:00:00,11495.0381,0.0,0.0,,9861.49,-0.0,9861.49,78961.65,178961.65,18996.75
21,Closed,Buy,5,2020-10-28 00:00:00,13654.2148,2021-05-24 00:00:00,34700.3633,0.0,0.0,,105230.74,-0.0,105230.74,173396.51,273396.51,0.0
23,Closed,Buy,5,2021-08-20 00:00:00,46723.1211,2021-12-28 00:00:00,50679.8594,0.0,0.0,,19783.69,-0.0,19783.69,133066.41,233066.41,40330.1
24,Closed,Sell,5,2021-12-28 00:00:00,50679.8594,2022-04-08 00:00:00,43505.1367,0.0,0.0,,35873.61,-0.0,35873.61,168940.02,268940.02,4456.49
26,Closed,Sell,5,2022-05-13 00:00:00,29030.9102,2022-09-16 00:00:00,19704.0059,0.0,0.0,,46634.52,-0.0,46634.52,143203.41,243203.41,30193.1
29,Closed,Buy,5,2023-01-26 00:00:00,23108.9551,2023-06-16 00:00:00,25575.2832,0.0,0.0,,12331.64,-0.0,12331.64,135594.25,235594.25,37802.26
33,Closed,Buy,5,2023-10-29 00:00:00,34089.3711,2024-05-30 00:00:00,67576.0859,0.0,0.0,,167433.57,-0.0,167433.57,204404.9,304404.9,0.0
34,Closed,Sell,5,2024-05-30 00:00:00,67576.0859,2024-06-22 00:00:00,64113.8633,0.0,0.0,,17311.11,-0.0,17311.11,221716.01,321716.01,0.0
37,Closed,Buy,5,2024-10-23 00:00:00,67362.375,2024-12-31 00:00:00,93429.2031,0.0,0.0,,130334.14,-0.0,130334.14,268080.91,368080.91,0.0

Losing Trades

,State,Order_Type,Volume,Open_Time,Open_Price,Close_Time,Close_Price,Stop_Loss,Limit,Info,Profit,Commission,Net_Profit,Cumulative_Profit,Balance,Drawdown
0,Closed,Sell,5,2015-02-21 00:00:00,243.752,2015-03-21 00:00:00,261.644,0.0,0.0,,-89.46,-0.0,-89.46,-89.46,99910.54,0.0
1,Closed,Buy,5,2015-03-21 00:00:00,261.644,2015-05-02 00:00:00,232.341,0.0,0.0,,-146.51,-0.0,-146.51,-235.97,99764.03,146.51
2,Closed,Sell,5,2015-05-02 00:00:00,232.341,2015-07-03 00:00:00,255.459,0.0,0.0,,-115.59,-0.0,-115.59,-351.56,99648.44,262.1
3,Closed,Buy,5,2015-07-03 00:00:00,255.459,2015-09-11 00:00:00,238.329,0.0,0.0,,-85.65,-0.0,-85.65,-437.21,99562.79,347.75
4,Closed,Sell,5,2015-09-11 00:00:00,238.329,2015-11-02 00:00:00,325.942,0.0,0.0,,-438.06,-0.0,-438.06,-875.27,99124.73,785.81
6,Closed,Sell,5,2016-02-26 00:00:00,424.629,2016-03-28 00:00:00,426.548,0.0,0.0,,-9.59,-0.0,-9.59,-391.42,99608.58,301.96
8,Closed,Sell,5,2016-08-30 00:00:00,574.114,2016-10-20 00:00:00,630.663,0.0,0.0,,-282.74,-0.0,-282.74,63.67,100063.67,282.74
11,Closed,Buy,5,2018-06-08 00:00:00,7685.1401,2018-06-17 00:00:00,6545.5298,0.0,0.0,,-5698.05,-0.0,-5698.05,54143.61,154143.61,5698.05
12,Closed,Sell,5,2018-06-17 00:00:00,6545.5298,2018-08-29 00:00:00,7091.71,0.0,0.0,,-2730.90,-0.0,-2730.9,51412.71,151412.71,8428.95
13,Closed,Buy,5,2018-08-29 00:00:00,7091.71,2018-09-17 00:00:00,6514.0601,0.0,0.0,,-2888.25,-0.0,-2888.25,48524.46,148524.46,11317.2
17,Closed,Buy,5,2020-02-05 00:00:00,9183.416,2020-03-28 00:00:00,6467.2539,0.0,0.0,,-13580.81,-0.0,-13580.81,84377.59,184377.59,13580.81
18,Closed,Sell,5,2020-03-28 00:00:00,6467.2539,2020-05-21 00:00:00,9522.7402,0.0,0.0,,-15277.43,-0.0,-15277.43,69100.16,169100.16,28858.24
20,Closed,Sell,5,2020-10-19 00:00:00,11495.0381,2020-10-28 00:00:00,13654.2148,0.0,0.0,,-10795.88,-0.0,-10795.88,68165.77,168165.77,29792.63
22,Closed,Sell,5,2021-05-24 00:00:00,34700.3633,2021-08-20 00:00:00,46723.1211,0.0,0.0,,-60113.79,-0.0,-60113.79,113282.72,213282.72,60113.79
25,Closed,Buy,5,2022-04-08 00:00:00,43505.1367,2022-05-13 00:00:00,29030.9102,0.0,0.0,,-72371.13,-0.0,-72371.13,96568.89,196568.89,76827.62
27,Closed,Buy,5,2022-09-16 00:00:00,19704.0059,2022-09-23 00:00:00,19412.4004,0.0,0.0,,-1458.03,-0.0,-1458.03,141745.38,241745.38,31651.13
28,Closed,Sell,5,2022-09-23 00:00:00,19412.4004,2023-01-26 00:00:00,23108.9551,0.0,0.0,,-18482.77,-0.0,-18482.77,123262.61,223262.61,50133.9
30,Closed,Sell,5,2023-06-16 00:00:00,25575.2832,2023-07-14 00:00:00,31474.7207,0.0,0.0,,-29497.19,-0.0,-29497.19,106097.06,206097.06,67299.45
31,Closed,Buy,5,2023-07-14 00:00:00,31474.7207,2023-09-03 00:00:00,25869.4727,0.0,0.0,,-28026.24,-0.0,-28026.24,78070.82,178070.82,95325.69
32,Closed,Sell,5,2023-09-03 00:00:00,25869.4727,2023-10-29 00:00:00,34089.3711,0.0,0.0,,-41099.49,-0.0,-41099.49,36971.33,136971.33,136425.18
35,Closed,Buy,5,2024-06-22 00:00:00,64113.8633,2024-07-12 00:00:00,57341.1953,0.0,0.0,,-33863.34,-0.0,-33863.34,187852.67,287852.67,33863.34
36,Closed,Sell,5,2024-07-12 00:00:00,57341.1953,2024-10-23 00:00:00,67362.375,0.0,0.0,,-50105.90,-0.0,-50105.9,137746.77,237746.77,83969.24

Average Win: 40952.36 USD
Average Loss: -17598.04 USD
Total Winning Trades: 16
Total Losing Trades: 22
Win Rate: 42.11%
Profit Factor: 1.69
Risk-Reward Ratio: 2.33

  Order_Type Net_Profit
0        Buy  367004.08
1       Sell  -98923.17

Maximum Drawdown: 136425.18 USD
Sharpe Ratio: 0.36
Sortino Ratio: 0.12
Total Net Profit: 268080.91 USD
Final Balance: 368080.91 USD
========================================

True